import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  deep_dive: [{ type: "autogenerated", dirName: "Deep dive" }],
  M1GP: [{ type: "autogenerated", dirName: "M1 GP" }],
  M2GP: [{ type: "autogenerated", dirName: "M2 GP" }],
}

export default sidebars
